server:
  port: 9090

spring:
  application:
    name: kafka-integration
  kafka:
    admin:
      auto-create: false


app:
  kafka:
    props:
      common:
        bootStrapServers: localhost:9092
        topic: kafka.spring.topic
      consumer:
        groupId: spring-app-group


